/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ridge-racer-psx)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* confirmed: USA state table index 1; entry increments 0x80176AE4. Live playable race verified. */
#define PSX_FN_RaceMain 0x800143CCu
#define func_800143CC RaceMain  /* alias */

/* guessed: USA car-update call at 0x8001C018; per-update integer dynamics/input. Units under investigation. */
#define PSX_FN_CarSimulateCandidate 0x800195B0u
#define func_800195B0 CarSimulateCandidate  /* alias */

/* guessed: USA race handler calls with player structure 0x80080194; integration/collision candidate. */
#define PSX_FN_CarUpdateCandidate 0x8001BD80u
#define func_8001BD80 CarUpdateCandidate  /* alias */

/* confirmed: USA car draw path: a0 owner structure, type+2 indexes model table 0x80056B40; composes car/camera matrices. */
#define PSX_FN_RenderCar 0x80020BB0u
#define func_80020BB0 RenderCar  /* alias */

/* confirmed: Reads SDK packet at 0x80176948; digital path decodes buttons and rising edges. Main returns to 0x80011CA0. */
#define PSX_FN_ReadPad 0x8002E0BCu
#define func_8002E0BC ReadPad  /* alias */

/* confirmed: USA model dispatcher: a2 model ID, 16-byte directory, six primitive groups. GTE transform established by caller. */
#define PSX_FN_RenderModel 0x800348E8u
#define func_800348E8 RenderModel  /* alias */

/* confirmed: Alternate model dispatcher with the same a2 ID and context+8 directory; used by 0x800158E8 scenery lists and effects. */
#define PSX_FN_RenderModelSubdivided 0x80034F78u
#define func_80034F78 RenderModelSubdivided  /* alias */

/* confirmed: Alternate model dispatcher used by the 0x800159F8 scenery list; same GTE transform and six-group model directory. */
#define PSX_FN_RenderModelClipped 0x80035F28u
#define func_80035F28 RenderModelClipped  /* alias */

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80040004u
#define func_80040004 BootEntry  /* alias */

/* guessed: Main-loop call returns to 0x80011C4C after state handler. SDK synchronization candidate. */
#define PSX_FN_DrawSync 0x80041538u
#define func_80041538 DrawSync  /* alias */

/* confirmed: Copies five words at a0 to GTE rotation control registers 0..4. Race passes 0x801ECD60. */
#define PSX_FN_SetRotationMatrix 0x80047324u
#define func_80047324 SetRotationMatrix  /* alias */
